### ISSUE TITLE
allow use link in href atribute

### ISSUE THREAD

**Issue by jasomdotnet** [englishextra/iframe-lightbox#15]
Now, in href atribute is `javascript:void(0);`. Allow to use real link and initialize lightbox different way. Exchange it with `data-src`.

**Comment by englishextra** [comment]
So that if the link is not JS initialised it will lead directly to the iframe URL?

**Comment by jasomdotnet** [comment]
> So that if the link is not JS initialised it will lead directly to the iframe URL

Not sure what you mean by your question exactly, but if your are asking "is it OK, to 'iframe' URL specified in `href` tag", then I say yes.

You may want to leave additional "iframe url" configuration within `data-src` tag, but is there any reason to do that? Most of lightboxes I have met is 'iframing' href link and I think it's great behaviour especially when JavaScript is turned-off.

**Comment by englishextra** [comment]
@jasomdotnet It's all right

1) leave `data-src` for compatibility; actually there was the reason why `data-src` was used and `href` was dead but it doesn't matter now
2) `href` will be used for iframe `src`

I need to rewrite readme and demo.html, thanks - that was a very good hint.

**Comment by englishextra** [comment]
@jasomdotnet v0.2.3 published on NPM

**Comment by jasomdotnet** [comment]
perfect!

**Comment by a1e7de48f89e** [comment]
Just to clarify, since you write

> `data-src` is deprecated, but supported for compatibility.

Right now (in `0.2.8`), when you have __both__ `href` and `data-src`, it will take the value from `data-src` as the iframe target over the `href` value (see [here](https://github.com/englishextra/iframe-lightbox/blob/v0.2.8/js/iframe-lightbox.js#L191)).

I think this is good, because it allows the following:

- Have the `href` behave normally and link to a page that has header, navigation, footer etc. for SEO reasons (since any search engine will likely ignore the `click` handler and just follow the `href` link instead)
- Add a parameter to the `data-src` query string (e.g., `?lightbox=1`) to programmatically remove header, navigation, footer etc. server-side when the page is opened in a lightbox and/or modify the rendered page in other ways

So, imo, I would just keep the behaviour as is and __don't__ eventually remove `data-src` in an upcoming version.

**Comment by englishextra** [comment]
@mserajnik 

```js
this.iframeSrc = this.src || this.href || "";
```
This behaviour is not gonna change. You are right, It's my overdirectorial to name `data-src` deprecated

Both methods to get source are handy

So I'll have to change that `deprecated` statement to as `alternative` or `interchangeable` methods

Thanks to help avoid this ambiguity

BTW This lib https://github.com/englishextra/img-lightbox has the same behaviour - the only difference is that it walks all the links on its own while with `iframe-lightbox` you select link elements by yourself.

UPD Changed that in `README.md` and `index.html`
