### ISSUE TITLE
Close Link

### ISSUE THREAD

**Issue by luismigueloliveira** [englishextra/iframe-lightbox#21]
Hi,

i want to creat a link with my own link and with a button to close the lightwindow.

There is any way to do it?

thanks

**Comment by englishextra** [comment]
@luismigueloliveira Hi. How do you mean?

When the light-box with embedded video or site is active, you don't have any single place to place a button of your own.

![2020-09-14_144220](https://user-images.githubusercontent.com/537127/93081898-a44a0e00-f698-11ea-90d5-862bd04a9fd7.png)

**Comment by luismigueloliveira** [comment]
I want to use my own link.

Like this
http://megadrive.mercatura.pt/luis/lightbox/index.php

**Comment by englishextra** [comment]
@luismigueloliveira Since you can close light-box by clicking on any surrounding dark background, there is no public API for custom close button.

Also there is no easy way to call JS on parent document  from embedded file via iframe because its unsafe

So,

1) There is no public api for closing lightbox using custom elements
2) Calling JS from iframe and execute it for parent document has always been tricky https://stackoverflow.com/questions/2161388/calling-a-parent-window-function-from-an-iframe

**Comment by englishextra** [comment]
Adding public API for closing will grow the code base and is likely to be an overkill
